language: objective-c
rvm: 1.9.3
env:
  - XCWORKSPACE="Example/MMFlowViewDemo.xcworkspace"
script: xcodebuild -workspace Example/MMFlowViewDemo.xcworkspace -scheme MMFlowViewDemo CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test
