language: objective-c
rvm: 1.9.3
before_install:
   - brew update
   - brew install xctool
script: xctool -workspace MMFlowViewDemo.xcworkspace -scheme MMFlowViewDemo_CI CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test
